services:
  - type: web
    name: crypto-sentinel
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r CryptoSentinel/requirements.txt
    startCommand: gunicorn --chdir CryptoSentinel app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true
